### ISSUE TITLE
So

### ISSUE THREAD

**Issue by Nimolas** [wagawgniwagagagas/blooket-hack#1]
a few questions. 

Will he make a new discord server?

is this the end?

What happened to all of his social media accs?

tell him I said good luck

**Comment by Rentuh** [comment]
Is this potentially a alt account for him? This is what redirects when you go to his website glizzers.xyz

**Comment by archn2** [comment]
Is this you, Glixzzy? If so, sorry about everything that happened.

**Comment by Rentuh** [comment]
If anybodys reading this, this shit isnt over
Get on reddit and join r/TeamGliz
WE WILL EXPOSE BEN GOD DAMMIR

**Comment by IcyonGit** [comment]
> If anybodys reading this, this shit isnt over Get on reddit and join r/TeamGliz WE WILL EXPOSE BEN GOD DAMMIT

What do you mean "expose ben"? What did ben do?

**Comment by SecretAgent55** [comment]
> If anybodys reading this, this shit isnt over Get on reddit and join r/TeamGliz WE WILL EXPOSE BEN GOD DAMMIT

![#FreeGliz!](https://user-images.githubusercontent.com/93560458/154981670-74e06a44-a359-48e8-bbf7-d454306c810b.gif)

**Comment by Gamehacker69** [comment]
he will be remembered but i dont think this is the end of gliz

**Comment by Piplup7575** [comment]
_slow clap_
and I wondered why the repo/account disappeared
it was fun while it lasted, too bad this happened.

**Comment by pazza223** [comment]
gliz will live on, in one way or another... maby a open sorce remake of the hacks? idk, just he piorneard the blooket hacks and in a year I will make a vidio on the "evalushion of blooket hacks" or somthing. all I know is this is not the end!

**Comment by yodaluca23** [comment]
I was talking to Gliz on Discord earlier today and yea, he got a cease and disease letter from Blooket. I don't think they are as much mad about the cheats/injectables/bookmarklets, (whatever u wanna call them) as they are about him hacking into their Twitter... but he doesn't seem like he will be doing anything to do with Blooket anytime soon when I talked to him... I don't know if this is an alt made by Gliz or not, but if it is please Gliz I will stand for you and everything you've done. #FreeGliz

- [ ]

**Comment by pazza223** [comment]
@yodaluca23 do you think that another blooket hack creator will take the spotlight or will there be no more hacks. also if you alredy know a alternitive let me know!

**Comment by yodaluca23** [comment]
@pazza223 SchoolCheats.net has already announced on their Discord server that they will be supposedly be taking over the making of them, but nobodies ever going to be as good as Gliz... Also, don't know how they would even sue him, sense no one even knows who he is.....

**Comment by pazza223** [comment]
@yodaluca23 I am most of the time at school, and am the one suplying it to my frends, and showing them how, do you know how to get into schoolcheats.net without it being hacked (and yes, I have tryed the unblocking chrome exstentions)

**Comment by yodaluca23** [comment]
> @yodaluca23 I am most of the time at school, and am the one suplying it to my frends, and showing them how, do you know how to get into schoolcheats.net without it being hacked (and yes, I have tryed the unblocking chrome exstentions)
> 
> 
> 
> #freegliz

Yes I am the same way at my school what you can do is get them at home set them up as bookmarklets, then you can export the folder with all of the bookmarklets into a .html file which you and your friends could import and use at school. Of course this would require a lot of effort because you would have to do it any time they update any of the scripts...

If schoolcheats.net does consistently keep them updated then I may put up a google site with a .html file with them all organized in folders and sub folders. And I may, (if I ever do get accepted or on board with SchoolCheats at all) post the .html file on the schoolcheats.net page itself (of course I have not even thought about publishing the .html files before but, with all this chaos going on right now and with schoolcheats.net potentially taking over it may be the perfect time to do so. Also of course I have had no contact with any of the SchoolCheats.net devs other then Gliz about this...)

**Comment by pazza223** [comment]
@yodaluca23 that is what i was doing with gliz's stuff, but i did not know that school cheats had the copy thong, soooooo ya. also is there a way to do it not with school cheats or gliz becuse it is easyer to do it github is not blocked at school for some reson (idk why becuse we never use it)

**Comment by yodaluca23** [comment]
No, I don't know of any other way other than using the console and I HIGHLY doubt that that is unblocked at your school... The reason  GitHub is unblocked is most likely because of any coding classes or clubs that would use it to post their code/programs...

**Comment by wagawgniwagagagas** [comment]
its back https://github.com/glixzzy/blooket-hack

**Comment by yodaluca23** [comment]
Remake right before all the chaos https://github.com/yodaluca23/blooket-hack
