### ISSUE TITLE
RESTORATION OF BLOOKET HACKS

### ISSUE THREAD

**Issue by akim-sys-code** [wagawgniwagagagas/blooket-hack#3]
Will these hacks ever return?

**Comment by ZasticBradyn** [comment]
No, Gliz can no longer legally create blooket hacks, because blooket sent him a [Cease and Desist](https://en.wikipedia.org/wiki/Cease_and_desist) letter.

**Comment by Gamehacker69** [comment]
it's basically just a warning though he still could it just might get involved latter if he does not stop

**Comment by cocoloko867** [comment]
Why

**Comment by pazza223** [comment]
@cocoloko867 becuse he hacked the blooket twiter probaly...

**Comment by wagawgniwagagagas** [comment]
its back https://github.com/glixzzy/blooket-hack

**Comment by yodaluca23** [comment]
Remake right before all the chaos https://github.com/yodaluca23/blooket-hack
